### ISSUE TITLE
How to open img_rois_Stardist_Subset.zip using QuPath?

### ISSUE THREAD

**Issue by YaoShuai-hub** [10XGenomics/HumanColonCancer_VisiumHD#10]
Hello，I was wondering how to open img_rois_Stardist_Subset.zip using QuPath? I can open .tif file, but can't open  img_rois_Stardist_Subset.zip of segmented nuclei for the selected region. Could you please tell me how to use QuPath open it? Such as File->Open->... By the way, I used QuPath on Ubuntu.

**Comment by jpromeror** [comment]
Hello!

There are 2 different ways to import the `img_rois_Stardist_Subset.zip` annotations into QuPath:

1.  You can just drag and drop the file into the QuPath window.

2. `Extensions > ImageJ > Import ImageJ ROIs`

**Comment by YaoShuai-hub** [comment]
Thanks a lot!
