### ISSUE TITLE
Inconsistent Level 2 cell type number

### ISSUE THREAD

**Issue by YaoShuai-hub** [10XGenomics/HumanColonCancer_VisiumHD#11]
Hello! I ran into a problem while running Methods/FlexSingleCell.R. It seems that Level 2 has 46 subcluster, but it gives 48 Level 2 cell types. I'm wondering how you got this level 2 cell type after FindAllMarkers. Could you please share the cell type marker list?

My Seurat version is 5.1.0.

outputs:
> Level2Clusters<-data.frame(ID=sort(unique(MetaDataSubClusters$Level2)),
                            Label=c("Plasma","Mature B", ...)
Error data.frame(ID = sort(unique(MetaDataSubClusters$Level2)), Label = c("Plasma", : 
  Parameter values mean different number of rows: 46, 48

**Comment by YaoShuai-hub** [comment]
Level 1 cell type annotation are also incorrect
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/128676920/cb20014a-9ffe-43ae-b224-680eddfb032d)

**Comment by YaoShuai-hub** [comment]
Strangely, the shape of the read map is not the same as that of the Supplemental Figure 2 umap
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/128676920/bbef992a-a61c-4040-81f9-586f970602fb)
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/128676920/7c404150-a0bb-4858-9e4e-a0aebe388b33)

**Comment by jpromeror** [comment]
Hello!

It looks that the UMAP and number above are showing only the "sketched" cells in the Seurat object.
Could you double check if the projection to the full dataset was done correctly?

**Comment by YaoShuai-hub** [comment]
Hi! 
Thanks for your reply! I changed DefaultAssay(ColonCancer_Flex) <- "RNA". Except for that, I haven't made any changes to the clustering parameters and code. But Level 1 has 33 clusters now. 
Could you please offer me the intermediate file with annotations for each cell? 
The UMAP:
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/128676920/a446e474-2a8e-4364-9557-5ecb95a507c1)

**Comment by LingyuLi-math** [comment]
I meet the same problem:

**Comment by LingyuLi-math** [comment]
I meet the same problem when run:
`## Rename Clusters
Level2Clusters<-data.frame(ID=sort(unique(MetaDataSubClusters$Level2)),
                           Label=c("Plasma","Mature B","vSM","Memory B",
                                   "Endothelial","Myofibroblast","Lymphatic Endothelial",
                                   "CAF","Fibroblast","Fibroblast","Pericytes","Myofibroblast","Myofibroblast",
                                   "Vascular Fibroblast","Proliferating Fibroblast","Adipocyte",
                                   "Goblet","Enterocyte","Tuft","Macrophage","Mast","Mast",
                                   "Macrophage","Neutrophil","Proliferating Macrophage","mRegDC","cDC I","pDC",
                                   "Enteric Glial","vSM","Enteric Glial","Neuroendocrine","Macrophage",
                                   "Epithelial","SM Stress Response","Smooth Muscle","vSM","Unknown III (SM)",
                                   "CD4 T cell","CD8 Cytotoxic T cell","NK cell","Unknwon I (Immune)",
                                   "Tumor I","Tumor II","Tumor III","Tumor IV","Tumor V","Proliferating Immune II"))`
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/64261429/40082e2c-e10f-47b9-aa8d-68756a143988)

**Comment by jpromeror** [comment]
Hello!

Sorry for the delayed response.

Thanks for highlighting this. I've identified a couple of errors and planning to update the code as soon as possible.
Also, we will upload a `MetaData` file with both Level1 and Level2 annotations.

Will update once it's completed.

**Comment by jpromeror** [comment]
You can find the annotations in the repository https://github.com/10XGenomics/HumanColonCancer_VisiumHD/blob/main/MetaData/SingleCell_MetaData.csv

Also addressed the inconsistency between number of clusters and cell type labels. 

Will close the issue, but feel free to reopen if something isn't working.

Thanks for catching this!
