### ISSUE TITLE
could not find function "Reference"

### ISSUE THREAD

**Issue by LingyuLi-math** [10XGenomics/HumanColonCancer_VisiumHD#12]
Hi , 

Thanks for contributing so great work!

When I run `reference <- Reference(FlexRef[,names(CTRef)], CTRef , colSums(FlexRef))` in '[Deconvolution.R](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/blob/main/Methods/Deconvolution.R)', it shows:
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/64261429/3a60749f-f724-4e8d-b1e1-09f911fb68e5)

Could you help me check this issue? Thanks a lot.

**Comment by jpromeror** [comment]
Hello!

`Reference` is a function from the [spaceXR](https://github.com/dmcable/spacexr) package.
Could you double check if the package was installed correctly and you are able to run `library(spacexr)`?

Let me know if that solves the problem.

**Comment by LingyuLi-math** [comment]
Yes, I have solved this issue by `remotes::install_github("dmcable/RCTD")` and `library(spacexr)`.

In this way, the functions `Reference()` and `SpatialRNA()` are run well Only the function `BlockXena()` is not defined, but it has no effect. It seems `XenaHD<-BlockXena$HD[Index]` is not used in further analysis.

But when I run `puck <- SpatialRNA(coords, counts, nUMI)`, it shows:
![image](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/assets/64261429/a2543f31-3edd-4cb8-97f4-969df9d09f90)

I found it will be solved by adding `rownames(coords) <- colnames(counts)`, before this line. Hope it will be helpful.

**Comment by jpromeror** [comment]
Ah! That line (`XenaHD<-BlockXena$HD[Index]`) shouldn't be there. However it doesn't affect the rest of the script. I will modify that part of the script.

Regarding the second part. There is a line of [code](https://github.com/10XGenomics/HumanColonCancer_VisiumHD/blob/1bf94034730af5a8a9d9525824be3d35d60d01dd/Methods/Deconvolution.R#L37) that does what you mention. 

Your solution could lead to errors if the barcodes in the `coords` and `counts` objects aren't sorted identically. 
I would recommend following the script instead.
