### ISSUE TITLE
Spacexr results for deconvolution

### ISSUE THREAD

**Issue by chiyuhao** [10XGenomics/HumanColonCancer_VisiumHD#16]
Hi, I noticed that the code does not set a random seed, so the output of spacexr is slightly different each time. Since the deconvolution process is very time-consuming, could you please consider providing the result file of the deconvolution as well? Thank you very much!

**Comment by jpromeror** [comment]
Hello!

Yesterday we added the corresponding files to the repo. You should be able to find them in the MetaData folder.

```
DeconvolutionResults_P1CRC.csv.gz 
DeconvolutionResults_P2CRC.csv.gz 
DeconvolutionResults_P5CRC.csv.gz
```

Let me know if something else is missing.

**Comment by chiyuhao** [comment]
Thank you very much for providing these files!

A small bug: I think when create data.frame with all Patient information, P1 sample is associated with Tumor II not Tumor III, and P2 is Tumor III not Tumor II based on the results in the paper.
`SampleData<-data.frame(Patient = c("P1CRC","P2CRC","P5CRC"),
                       PathSR=c("~/VisiumHD/PatientCRC1/outs/","~/VisiumHD/PatientCRC2/outs/","~/VisiumHD/PatientCRC5/outs/"),
                       Tumor = c("Tumor III","Tumor II","Tumor IV"))`
