### ISSUE TITLE
FastQ files for Chromium SIngle Cell Flex

### ISSUE THREAD

**Issue by kloot** [10XGenomics/HumanColonCancer_VisiumHD#17]
Hi,  
Thank you for making this great dataset available! 
I could not find the FastQ files from the Single Cell Flex experiments at https://www.10xgenomics.com/products/visium-hd-spatial-gene-expression/dataset-human-crc.
Are they available elsewhere?

**Comment by jpromeror** [comment]
Hello!

At this moment the fastqs are not available.

We are preparing the submission that will include all the raw data used in the manuscript (Flex, VisiumHD, Visium v2, Single Cell VDJ and Xenium). We will post it and update the page as soon as it is available.

Sorry for the inconvenience!

**Comment by kloot** [comment]
No worries, and thanks for clarifying, JP!

**Comment by cmiciano** [comment]
Any updates to publishing the raw data? I'm not familiar with the cellranger aggr output so I'm not sure where to find
aggregation_csv.csv and projection.csv from these lines in `FlexSingleCell.R`

```
MetaData<-read.csv(paste0(FlexOutPath,"aggregation_csv.csv"))
UMAP<-read.csv(paste0(FlexOutPath,"/analysis_csv/umap/gene_expression_2_components/projection.csv"))
```

**Comment by jpromeror** [comment]
Hi @cmiciano!

You can download those files here:
https://www.10xgenomics.com/products/visium-hd-spatial-gene-expression/dataset-human-crc

The UMAP can be found in the `clustering_analysis` file.

**Comment by jpromeror** [comment]
@kloot 
Hopefully is not too late, but all raw data (fastqs) is here:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE280318
