### ISSUE TITLE
Could you provide scRNA-seq reference data?

### ISSUE THREAD

**Issue by Yijia-Jiang** [10XGenomics/HumanColonCancer_VisiumHD#19]
Hello, could you provide with the processed and annotated scRNA-seq reference data, which is the "FlexSeuratV5.rds" in FlexSingleCell.R script? Thank you very much.

**Comment by jpromeror** [comment]
Hello!

I would recommend building it from scratch

Here are the links to the data:

The expression matrix (h5) 
https://www.10xgenomics.com/products/visium-hd-spatial-gene-expression/dataset-human-crc

cell type annotations
https://github.com/10XGenomics/HumanColonCancer_VisiumHD/tree/main/MetaData

**Comment by Yijia-Jiang** [comment]
Thank you very much. For the deconvolution step, did you downsample the reference data before applying it for deconvolution?

**Comment by jpromeror** [comment]
We didn't. We just excluded cell types with less than 25 cells.
Here is the code to the script we used:
https://github.com/10XGenomics/HumanColonCancer_VisiumHD/blob/main/Methods/Deconvolution.R
