### ISSUE TITLE
Could you provide the Xenium annotation data?

### ISSUE THREAD

**Issue by jincanke** [10XGenomics/HumanColonCancer_VisiumHD#21]
Hello, 
Congratulations on your impressive HD technology and paper (https://doi.org/10.1101/2024.06.04.597233)! We are interested in your data and would like to test it. I noticed that Figure 7 labeled the cells of the Xenium data. Could you kindly provide the cell annotations for the P2CRC sample (Xenium)? 
Thank you very much!

**Comment by jpromeror** [comment]
At this moment we don't have the Xenium cell type labels. We used different to label the cells shown in Figure 7. 
However, I do believe this information could be useful. Will aim to add it to the repository as soon as possible.

Will close the issue for now and will drop a reminder once the data is available.

Thanks!
