### ISSUE TITLE
Seurat R to python for 10X visium HD

### ISSUE THREAD

**Issue by jyxue9** [10XGenomics/HumanColonCancer_VisiumHD#22]
How to do it?

**Comment by jpromeror** [comment]
Hello!
Can you provide more details? I don't fully understand your question.

**Comment by jyxue9** [comment]
transfer data from Seurat v5 to Scanpy for Visium HD spatial transcriptomics analysis.  
Could you please help transfer object@images slot of a Seurat object to adata.uns["spatial"][library_id]["images"]?

**Comment by jpromeror** [comment]
I would suggest reaching to the developers of `Seurat`, in particular `SeuratDisk` (https://github.com/mojaveazure/seurat-disk). 

Closing the issue as the request is not related to this particular repository.
